import { useMemo, useState } from 'react'
import activityData from '../data/activity.json'
import projectsData from '../data/projects.json'
import snapshotsData from '../data/daily-snapshots.json'
import type { ActivityEntry, DailySnapshot, Project } from './types'
import { buildWeeklyActivity } from './lib/activity'
import { averageProgress, countActiveProjects, type StatusFilter } from './lib/projects'
import { calculateCurrentStreak, getTotalTrackedDays, toUtcDateString } from './lib/streak'
import { Header } from './components/Header'
import { StatCard } from './components/StatCard'
import { ProjectGrid } from './components/ProjectGrid'
import { ActivityChart } from './components/ActivityChart'
import { ActivityTimeline } from './components/ActivityTimeline'

const projects = projectsData as Project[]
const activity = activityData as ActivityEntry[]
const snapshots = snapshotsData as DailySnapshot[]

function IconProjects() {
  return (
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden>
      <path
        d="M4 7h16M4 12h10M4 17h14"
        stroke="currentColor"
        strokeWidth="1.8"
        strokeLinecap="round"
      />
    </svg>
  )
}

function IconFlame() {
  return (
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden>
      <path
        d="M12 3c2 3 1 5 1 5s3-1 3 4a5 5 0 1 1-10 0c0-4 3-6 6-9Z"
        stroke="currentColor"
        strokeWidth="1.6"
        strokeLinejoin="round"
      />
    </svg>
  )
}

function IconCalendar() {
  return (
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden>
      <rect x="3.5" y="5" width="17" height="15" rx="2" stroke="currentColor" strokeWidth="1.6" />
      <path d="M8 3.5v3M16 3.5v3M3.5 10h17" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" />
    </svg>
  )
}

function IconPulse() {
  return (
    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden>
      <path
        d="M3 12h4l2-5 3 10 2-5h7"
        stroke="currentColor"
        strokeWidth="1.6"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  )
}

export default function App() {
  const [filter, setFilter] = useState<StatusFilter>('all')
  const latestDate = snapshots.at(-1)?.date ?? toUtcDateString()

  const stats = useMemo(() => {
    const active = countActiveProjects(projects)
    const streak = calculateCurrentStreak(snapshots)
    const tracked = getTotalTrackedDays(snapshots)
    const avg = averageProgress(projects)
    const todayTasks = snapshots.find((s) => s.date === latestDate)?.completedTasks ?? 0
    return { active, streak, tracked, avg, todayTasks }
  }, [latestDate])

  const weekly = useMemo(
    () => buildWeeklyActivity(activity, latestDate),
    [latestDate],
  )

  return (
    <div className="app-shell min-h-screen text-ink">
      <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8">
        <Header subtitle="A polished sample dashboard for fictional development activity, project progress, and historical daily snapshots." />

        <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Key metrics">
          <StatCard
            label="Active projects"
            value={stats.active}
            hint="Currently in motion"
            icon={<IconProjects />}
            delayMs={40}
          />
          <StatCard
            label="Daily activity"
            value={stats.todayTasks}
            hint={`Tasks on ${latestDate}`}
            icon={<IconPulse />}
            delayMs={80}
          />
          <StatCard
            label="Current streak"
            value={`${stats.streak}d`}
            hint="Consecutive tracked days"
            icon={<IconFlame />}
            delayMs={120}
          />
          <StatCard
            label="Tracked days"
            value={stats.tracked}
            hint={`Avg progress ${stats.avg}%`}
            icon={<IconCalendar />}
            delayMs={160}
          />
        </section>

        <div className="mt-8 grid gap-6 lg:grid-cols-[1.15fr_0.85fr]">
          <div className="space-y-6">
            <ProjectGrid projects={projects} filter={filter} onFilterChange={setFilter} />
          </div>
          <div className="space-y-6">
            <ActivityChart days={weekly} />
            <ActivityTimeline entries={activity} projects={projects} />
          </div>
        </div>

        <footer className="mt-12 border-t border-edge/70 pt-6 text-sm text-muted">
          <p>
            DevPulse uses local JSON under <code className="font-mono text-accent/90">data/</code> as a
            sample historical record. Daily snapshots are generated by a script and GitHub Action for
            demo continuity—not for contribution farming.
          </p>
        </footer>
      </div>
    </div>
  )
}
